
.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. pwdh_qt test_pwdh_qt
clean: FORCE
	$(MAKE) -C .. pwdh_qt_clean test_pwdh_qt_clean
check: FORCE
	$(MAKE) -C .. test_pwdh_qt_check
pwdh-qt pwdh-qt.exe: FORCE
	 $(MAKE) -C .. pwdh_qt
apk: FORCE
	$(MAKE) -C .. pwdh_qt_apk
