dist_man1_MANS=

if BUILD_PWDHD
  dist_man1_MANS+=pwdhd.1
endif

if ENABLE_QT
  dist_man1_MANS+=pwdh-qt.1
endif

if BUILD_PWDH_CLI
  dist_man1_MANS+=pwdh-cli.1
endif

if BUILD_PWDH_TX
  dist_man1_MANS+=pwdh-tx.1
endif

if BUILD_PWDH_UTIL
  dist_man1_MANS+=pwdh-util.1
endif

if ENABLE_WALLET
if BUILD_PWDH_WALLET
  dist_man1_MANS+=pwdh-wallet.1
endif
endif
