name: pwdh-macos-node

services:
  pwdh-mainnet:
    image: pwdh-core-mainnet:latest
    platform: linux/amd64
    container_name: pwdh-macos-mainnet
    restart: unless-stopped
    command:
      - "-server=1"
      - "-listen=1"
      - "-bind=0.0.0.0"
      - "-discover=1"
      - "-txindex=1"
      - "-dnsseed=1"
      - "-printtoconsole=1"
      - "-conf=/etc/pwdh/pwdh.conf"
      - "-datadir=/var/lib/pwdh"
    volumes:
      - ./pwdh.conf:/etc/pwdh/pwdh.conf:ro
      - pwdh_data:/var/lib/pwdh

volumes:
  pwdh_data:
