server=1
listen=1
bind=0.0.0.0
discover=1
txindex=1
dnsseed=1
addnode=seed01.pwdh.org:37934
addnode=seed02.pwdh.org:37934
addnode=seed03.pwdh.org:37934
addnode=seed04.pwdh.org:37934
addnode=seed05.pwdh.org:37934
