#!/usr/bin/env bash
#
#  pwdhd The pwdh core server.
#
#
# chkconfig: 345 80 20
# description: pwdhd
# processname: pwdhd
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/pwdhd, see below
if [ -f /etc/sysconfig/pwdhd ]; then
        . /etc/sysconfig/pwdhd
fi

RETVAL=0

prog=pwdhd
# you can override the lockfile via PWDHD_LOCKFILE in /etc/sysconfig/pwdhd
lockfile=${PWDHD_LOCKFILE-/var/lock/subsys/pwdhd}

# pwdhd defaults to /usr/bin/pwdhd, override with PWDHD_BIN
pwdhd=${PWDHD_BIN-/usr/bin/pwdhd}

# pwdhd opts default to -disablewallet, override with PWDHD_OPTS
pwdhd_opts=${PWDHD_OPTS--disablewallet}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS $pwdhd $pwdhd_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog -t600
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
