description "Bitcoin Core Daemon"

start on runlevel [2345]
stop on starting rc RUNLEVEL=[016]

env PWDHD_BIN="/usr/bin/pwdhd"
env PWDHD_USER="pwdh"
env PWDHD_GROUP="pwdh"
env PWDHD_PIDDIR="/var/run/pwdhd"
# upstart can't handle variables constructed with other variables
env PWDHD_PIDFILE="/var/run/pwdhd/pwdhd.pid"
env PWDHD_CONFIGFILE="/etc/pwdh/pwdh.conf"
env PWDHD_DATADIR="/var/lib/pwdhd"

expect fork

respawn
respawn limit 5 120
kill timeout 600

pre-start script
    # this will catch non-existent config files
    # pwdhd will check and exit with this very warning, but it can do so
    # long after forking, leaving upstart to think everything started fine.
    # since this is a commonly encountered case on install, just check and
    # warn here.
    if ! grep -qs '^rpcpassword=' "$PWDHD_CONFIGFILE" ; then
        echo "ERROR: You must set a secure rpcpassword to run pwdhd."
        echo "The setting must appear in $PWDHD_CONFIGFILE"
        echo
        echo "This password is security critical to securing wallets "
        echo "and must not be the same as the rpcuser setting."
        echo "You can generate a suitable random password using the following "
        echo "command from the shell:"
        echo
        echo "bash -c 'tr -dc a-zA-Z0-9 < /dev/urandom | head -c32 && echo'"
        echo
        echo "It is recommended that you also set alertnotify so you are "
        echo "notified of problems:"
        echo
        echo "ie: alertnotify=echo %%s | mail -s \"Bitcoin Alert\"" \
            "admin@foo.com"
        echo
        exit 1
    fi

    mkdir -p "$PWDHD_PIDDIR"
    chmod 0755 "$PWDHD_PIDDIR"
    chown $PWDHD_USER:$PWDHD_GROUP "$PWDHD_PIDDIR"
    chown $PWDHD_USER:$PWDHD_GROUP "$PWDHD_CONFIGFILE"
    chmod 0660 "$PWDHD_CONFIGFILE"
end script

exec start-stop-daemon \
    --start \
    --pidfile "$PWDHD_PIDFILE" \
    --chuid $PWDHD_USER:$PWDHD_GROUP \
    --exec "$PWDHD_BIN" \
    -- \
    -pid="$PWDHD_PIDFILE" \
    -conf="$PWDHD_CONFIGFILE" \
    -datadir="$PWDHD_DATADIR" \
    -disablewallet \
    -daemon

